title: IPos Manuals
description: The place to be for IPOS documentation
theme: just-the-docs

url: https://bbcwiki.github.io
baseurl: /IPos-Manuals

search_enabled: true

aux_links:
  GitHub Repository:
    - https://github.com/BBCWiki/IPos-Manuals
